name: workshops
channels:
   - conda-forge
   - bioconda
dependencies:
   - python >=3.8,<3.13
   - biopython
   - blast
   - bwa
   - fastqc
   - fastqe
   - iqtree
   - itables
   - matplotlib
   - mlst
   - numpy
   - pandas
   - prokka
   - pysam
#  - python-igraph
   - bioconda::samtools >=1.7
   - seaborn
   - fastcluster
#  - snippy
   - snp-dists
#  - bioconda::snpeff=4.3
