name: workshops
channels:
    - conda-forge
    - bioconda
dependencies:
  - scikit-bio
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - fastqc
  - snippy
  - samtools
  - iqtree
  - prokka
  - mlst
