name: workshops
channels:
    - conda-forge
    - bioconda
dependencies:
#  - biopython
#  - blast
#  - bwa
#  - fastqc
#  - fastqe
#  - iqtree
#  - leidenalg
#  - matplotlib
#  - mlst
#  - numpy
#  - pandas
#  - prokka
  - pysam
#  - python-igraph
  - bioconda::samtools>=1.7
#  - scanpy
#  - scikit-bio
#  - seaborn
  - snippy
#  - snp-dists
  - bioconda::snpeff=4.3
