name: workshops
channels:
    - conda-forge
    - bioconda
dependencies:
  - biopython
  - blast
  - bwa
  - fastqc
  - fastqe
  - iqtree
  - leidenalg
  - matplotlib
  - mlst
  - numpy
  - pandas
  - prokka
  - pysam
  - python-igraph
  - samtools
  - scanpy
  - scikit-bio
  - seaborn
  - snippy
  - snp-dists
