name: workshops
channels:
   - conda-forge
   - bioconda
   - defaults
dependencies:
   - python >=3.8,<3.13
   - biopython
   - blast
   - bwa
   - fastqc
   - fastqe
   - iqtree=2.4
   - itables
   - matplotlib
   - numpy
   - pandas
   - prokka >=1.14
   - pysam
#  - python-igraph
   - bioconda::samtools >=1.7
   - seaborn
   - fastcluster
   - freebayes
   - snp-dists
#  - bioconda::snpeff=4.3

