name: workshops
channels:
    - conda-forge
    - bioconda
dependencies:
  - scikit-bio
  - pysam
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - fastqc
  - snippy
  - samtools
  - iqtree=2.1.2
  - prokka
  - mlst
  - blast
  - bwa
  - snp-dists
  - bakta
  - util-linux
  - scanpy
  - python-igraph
  - leidenalg
